# Generated by Django 5.0.2 on 2024-04-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_reading_time_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reading_time',
        ),
        migrations.AddField(
            model_name='post',
            name='readingtime',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
