# Generated by Django 5.0.2 on 2024-04-25 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_readingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='readingtime',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_file', models.ImageField(upload_to='post_image/', verbose_name='فایل تصویر')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.post', verbose_name='تصاویر')),
            ],
        ),
    ]
