# Generated by Django 5.0.2 on 2024-05-23 08:29

import blog.others
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_image_image_file_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to=blog.others.upload_to_author_directory),
        ),
    ]
