# Generated by Django 5.0.2 on 2024-05-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_account_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('تکنولوژی', 'تکنولوژی'), ('برنامه نویسی', 'برنامه نویسی'), ('سایر', 'سایر')], default='سایر', max_length=20),
        ),
    ]
